In [4]:
#load the data set  from iris 

from sklearn.datasets import load_iris

iris = load_iris()
x = iris.data
y = iris.target

print x.shape
print y.shape


(150L, 4L)
(150L,)


In [11]:
#load the relevant sklearn algorithms
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors =5)

In [12]:
#print the variable to see the paramters that can be tuned

print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


In [13]:
#fit the training data to the model.

knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [14]:
#predict the value using numpy arrray , returns numpy array

knn.predict([[3, 5, 4, 2]])

array([1])

In [15]:
x_new =[[1,4,5,2],[2,4,5,1]]
knn.predict(x_new)

array([1, 1])

In [17]:
# instantiate the model (using the value K=6)
knn = KNeighborsClassifier(n_neighbors=6)

# fit the model with data
knn.fit(x, y)

# predict the response for new observations
knn.predict(x_new)

array([1, 1])

In [18]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(x, y)

# predict the response for new observations
logreg.predict(x_new)



array([2, 2])